export { createApolloClient } from './apollo-client'
export { SCHEMA_INFO_QUERY } from './schema-info-query'
export type { SchemaInfo, SchemaInfoResponse } from './schema-info-query'
export { checkSchemaCompatibility } from './schema-compatibility'
export type { CompatibilityResult } from './schema-compatibility'
